# Generated by Django 5.0.3 on 2024-03-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move_In_Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_monthly', models.FloatField()),
                ('security_diposit', models.FloatField()),
                ('broker_fee', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='map_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='listing',
            name='move_in_cost',
            field=models.ManyToManyField(blank=True, to='listings.move_in_cost'),
        ),
    ]
