# Generated by Django 5.0.3 on 2024-03-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/%Y/%m/%d/'),
        ),
    ]
