# Generated by Django 5.0.3 on 2024-03-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_map_link',
        ),
        migrations.AddField(
            model_name='listing',
            name='map_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
