# Generated by Django 5.0.3 on 2024-03-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_address_address_map_link_listing_map_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='map_link',
        ),
        migrations.AddField(
            model_name='listing',
            name='map_iframe',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
