# Generated by Django 5.0.3 on 2024-03-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listing_map_link_listing_map_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status_color',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
