# Generated by Django 5.0.3 on 2024-03-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listing_status_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='status_color',
            new_name='lable_class',
        ),
    ]
