# Generated by Django 5.0.3 on 2024-03-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_rename_status_color_listing_lable_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lable_class',
            field=models.CharField(choices=[('card_label_for_rent', 'For Rent'), ('card_label_comming_soon', 'Comming Soon'), ('card_label_for_sale', 'For Sale'), ('card_label_sold', 'Sold')], max_length=100),
        ),
    ]
